import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { fetchPerpUsdtTickerRows } from '../src/shared/binance-markets.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APP_DIR = path.resolve(__dirname, '../app');
const DATA_DIR = path.resolve(__dirname, '../src/data');
const OUT_APP = path.join(APP_DIR, 'tickers.json');
const OUT_TS = path.join(DATA_DIR, 'bundled-tickers.gen.ts');

async function main() {
  const rows = await fetchPerpUsdtTickerRows();
  if (!rows || rows.length === 0) {
    console.warn(
      '[prefetch-tickers] Binance fetch failed or empty — leaving existing tickers.json + bundled-tickers.gen.ts unchanged (avoid shipping a short fallback list on CI).',
    );
    return;
  }
  const payload = JSON.stringify(rows);
  fs.mkdirSync(path.dirname(OUT_APP), { recursive: true });
  fs.mkdirSync(path.dirname(OUT_TS), { recursive: true });
  fs.writeFileSync(OUT_APP, payload);
  fs.writeFileSync(
    OUT_TS,
    `/** Auto-generated by scripts/prefetch-tickers.ts — do not edit. */\nexport const BUNDLED_TICKERS = ${payload} as { symbol: string; lastPrice: string; priceChangePercent: string; quoteVolume: string }[];\n`,
  );
  console.log(`[prefetch-tickers] wrote ${rows.length} rows -> ${OUT_APP} + ${OUT_TS}`);
}

await main();
